### ISSUE TITLE
[Traceback] geoip2.errors.AddressNotFoundError: The address aaa.xxx.yyy.zzz is not in the database.

### ISSUE THREAD

**Issue by 1wilkens** [UHH-ISS/honeygrove#35]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/app/honeygrove/services/TCPFlagService.py", line 150, in scanOpenSynConnections
    log.scan(item.sourceIP, item.destPort, item.timeStamp, 'syn')
  File "/app/honeygrove/log.py", line 346, in scan
    coordinates = get_coordinates(ip)
  File "/app/honeygrove/log.py", line 79, in get_coordinates
    resp = GEO_READER.city(ip)
  File "/usr/lib/python3.6/site-packages/geoip2/database.py", line 114, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/usr/lib/python3.6/site-packages/geoip2/database.py", line 195, in _model_for
    record = self._get(types, ip_address)
  File "/usr/lib/python3.6/site-packages/geoip2/database.py", line 191, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address aaa.xxx.yyy.zzz is not in the database.
```

**Comment by 1wilkens** [comment]
Fixed in https://github.com/UHH-ISS/honeygrove/commit/42834142a9f5c64719953925a7c27b94fda68f7b
