### ISSUE TITLE
[Traceback] builtins.ValueError: ('Stumped', b'\x01')

### ISSUE THREAD

**Issue by 1wilkens** [UHH-ISS/honeygrove#36]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python3.6/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python3.6/site-packages/twisted/conch/telnet.py", line 585, in dataReceived
    raise ValueError("Stumped", b)
builtins.ValueError: ('Stumped', b'\x01')
```

**Comment by ekaxis** [comment]
poderia dar mais detalhes de em que cenário o erro ocorre para que seja possível reproduzi-lo ?

**Comment by ekaxis** [comment]
na linha `97` no arquivo `HTTPService.py` adicionar o parâmetro `errors="ignore"`, ficaria: 
```
data = data.decode('utf-8', errors="ignore")
```
