### ISSUE TITLE
[Traceback] builtins.UnicodeDecodeError: 'unicodeescape' codec can't decode byte 0x5c in position 33: \ at end of string

### ISSUE THREAD

**Issue by 1wilkens** [UHH-ISS/honeygrove#37]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python3.6/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib/python3.6/site-packages/twisted/conch/ssh/transport.py", line 703, in dataReceived
    self.dispatchMessage(messageNum, packet[1:])
  File "/usr/lib/python3.6/site-packages/twisted/conch/ssh/transport.py", line 728, in dispatchMessage
    messageNum, payload)
--- <exception caught here> ---
  File "/usr/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python3.6/site-packages/twisted/conch/ssh/service.py", line 45, in packetReceived
    return f(packet)
  File "/app/honeygrove/services/SSHService.py", line 548, in ssh_USERAUTH_REQUEST
    rest = rest.decode("unicode_escape")
builtins.UnicodeDecodeError: 'unicodeescape' codec can't decode byte 0x5c in position 33: \ at end of string
```

**Comment by 1wilkens** [comment]
Fixed in https://github.com/UHH-ISS/honeygrove/commit/064fd5c0922d512b46eaf811008b5cf6bbcd3c95
