### ISSUE TITLE
Traceback in HTTP logging

### ISSUE THREAD

**Issue by 1wilkens** [UHH-ISS/honeygrove#40]
```
2020-07-22T08:49:51.464529 [REQUEST] HTTP, 195.54.160.21:37844->195.37.209.20:80, Lat: --, Lon: --, /?XDEBUG_SESSION_START=phpstorm, , GET
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, args, kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, args, *kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/usr/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/app/honeygrove/services/HTTPService.py", line 197, in dataReceived
    log.response("HTTP", remote.host, remote.port, local.host, local.port, self.page, login_string, "404 NOT FOUND")
builtins.UnboundLocalError: local variable 'login_string' referenced before assignment
```

**Comment by ekaxis** [comment]
basta criar variável `login_string` antes da instrução `if` da linha `122`, ex: `login_string = ""` no arquivo `honeygrove/services/HTTPService.py`
